language: cpp
os: linux
dist: xenial
compiler:
  - gcc
  - clang

addons:
    apt:
        update: true
        packages:
            - texlive
            - texlive-generic-recommended
            - texlive-extra-utils
            - texlive-latex-extra
            - texlive-font-utils
            - ghostscript

linux-ppc64le: &linux-ppc64le
  os: linux-ppc64le
  addons:
      apt:
          update: true
          packages:
              - texlive
              - texlive-generic-recommended
              - texlive-extra-utils
              - texlive-latex-extra
              - texlive-font-utils
              - ghostscript
              - cmake
              - cmake-data

jobs:
    include:
        - <<: *linux-ppc64le
          compiler: gcc
        - <<: *linux-ppc64le
          compiler: clang
        - os: osx
          compiler: clang

before_script:
    - |
      if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
        printf "[requires]
        libxml2/2.9.8@bincrafters/stable
        libiconv/1.15@bincrafters/stable
        [build_requires]
        cmake_installer/3.10.0@conan/stable" >> conanfile.txt;
      fi;
      if [ "${TRAVIS_OS_NAME}" == "linux-ppc64le" ]; then
        printf "[requires]
        libxml2/2.9.8@bincrafters/stable" >> conanfile.txt;
      fi;
      if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        printf "[requires]
        libxml2/2.9.8@bincrafters/stable
        libiconv/1.15@bincrafters/stable
        qt/5.11.3@bincrafters/stable
        [options]
        qt:shared=False" >> conanfile.txt;
      fi;
    - if [ "${TRAVIS_OS_NAME}" == "linux" ] || [ "${TRAVIS_OS_NAME}" == "linux-ppc64le" ]; then
        pip install --quiet --user conan;
      fi;
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        pip install --upgrade pip;
        sudo mkdir -p /usr/local/man;
        sudo chown -R "${USER}:admin" /usr/local/man;
        pip install --quiet conan;
        export HOMEBREW_NO_AUTO_UPDATE=1;
        brew install ghostscript;

        travis_wait brew cask install mactex-no-gui;
        curl -O -L http://mirrors.ctan.org/support/epstopdf.zip;
        unzip epstopdf.zip;
        mkdir -p /Users/travis/Library/TeX/texbin/;
        mv epstopdf/epstopdf.pl /Users/travis/Library/TeX/texbin/epstopdf;
        chmod a+x /Users/travis/Library/TeX/texbin/epstopdf;
        rm -rf epstopdf*;
        export PATH=/Users/travis/Library/TeX/texbin:/Library/TeX/texbin:$PATH;
      fi;
    - |
        conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan;
        conan install . -g virtualrunenv --build missing --update;
        source activate_run.sh;

script:
    - mkdir build
    - cd build
    - cmake --version;
    - cmake -G "Unix Makefiles" -Dbuild_doc=ON -Dbuild_wizard=ON ..
    - make
    - make tests
    - make docs
